[package]
name = "cyclonedds-sys"
version = "0.1.0"
edition = "2021"
include = ["../cyclonedds/", "src/", "build.rs", "wrapper.h" ]
[dependencies]


[build-dependencies]
bindgen = "0.65.0"
cmake = "0.1.48"