name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  # Supply additional clang arguments for bindgen to avoid errors in glibc headers
  BINDGEN_EXTRA_CLANG_ARGS: >
    -D__GLIBC_USE(x)=
    -D__GNUC_PREREQ(a,b)=0
    -D__BEGIN_DECLS=
    -D__END_DECLS=
    -D__STDC__=1
    -D__STDC_VERSION__=201112L
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake clang
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
